import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopBar from '@/app/components/Topbar'
import Navbar from '@/app/components/Navbar'
import Footer from '@/app/components/footer'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-Commerce Hackathon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <TopBar/>
        <Navbar/>
        
        {children}
        <Footer/>
        
        </body>
        
    </html>
  );
}